# Generated by Django 2.1.3 on 2018-12-03 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='commentator',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
